server:
  port: 9093

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@web-project.ie0jgnl.mongodb.net/?retryWrites=true&w=majority
      database: ratings
  application:
    name: RATING-SERVICE

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

