server:
  port: 9095

spring:
  application:
    name: CONFIG-SERVER-SERVICE

  cloud:
    config:
      server:
        git:
          uri: https://github.com/traineeEngineer/microservice-commoin-config.git
          clone-on-start: true


